// Copyright 2026 Cloudsmith Ltd. All rights reserved.

export default {
  mutate: [
    "domain/authCapabilities.js",
    "domain/installGuidanceSupport.js",
    "domain/packageActionCapabilities.js",
    "util/searchQueryBuilder.js",
    "util/vulnerabilityReportProjection.js",
    "util/externalNavigation.js",
    "util/upstreamOperationScheduler.js:141-219",
    "util/vulnerabilityStateService.js:616-718",
    "util/installCommandBuilder.js:650-830",
  ],
  testRunner: "mocha",
  testFiles: [
    "test/authCapabilities.test.js",
    "test/installCommandBuilder.test.js",
    "test/installGuidanceSupport.test.js",
    "test/packageActionCapabilities.test.js",
    "test/searchQueryBuilder.test.js",
    "test/vulnerabilityReportProjection.test.js",
    "test/externalNavigation.test.js",
    "test/upstreamOperationScheduler.test.js",
    "test/vulnerabilityStateService.test.js",
  ],
  mochaOptions: {
    ui: "tdd",
    spec: [
      "test/authCapabilities.test.js",
      "test/installCommandBuilder.test.js",
      "test/installGuidanceSupport.test.js",
      "test/packageActionCapabilities.test.js",
      "test/searchQueryBuilder.test.js",
      "test/vulnerabilityReportProjection.test.js",
      "test/externalNavigation.test.js",
      "test/upstreamOperationScheduler.test.js",
      "test/vulnerabilityStateService.test.js",
    ],
    "no-config": true,
    "no-package": true,
    "no-opts": true,
  },
  coverageAnalysis: "perTest",
  ignoreStatic: true,
  reporters: ["clear-text", "progress", "json", "html"],
  jsonReporter: { fileName: ".quality/mutation/mutation.json" },
  htmlReporter: { fileName: ".quality/mutation/mutation.html" },
  incrementalFile: ".quality/mutation/stryker-incremental.json",
  tempDirName: ".stryker-tmp",
  cleanTempDir: "always",
  ignorePatterns: [
    ".vscode-test",
    ".quality",
    "internal_docs",
    "out",
    "coverage",
    "*.vsix",
  ],
  concurrency: 4,
  timeoutMS: 10_000,
  // The wrapper applies the measured core and per-file changed-mode floors.
  // A single Stryker break value cannot represent both aggregate and scoped runs.
  thresholds: { high: 95, low: 90, break: 0 },
  allowEmpty: false,
};
